config/routes.rb
Rails.application.routes.draw do

  
  devise_for :sellers, path: 'sellers', controllers: { sessions: "sellers/sessions", confirmations: "sellers/confirmations", passwords: "sellers/passwords", unlocks: "sellers/unlocks"}
  devise_for :buyers, path: 'buyers', controllers: { sessions: "buyers/sessions", confirmations: "buyers/confirmations", passwords: "buyers/passwords", unlocks: "buyers/unlocks"}
  devise_for :auctioneers, path: 'auctioneers', controllers: { sessions: "auctioneers/sessions", confirmations: "auctioneers/confirmations", passwords: "auctioneers/passwords", unlocks: "auctioneers/unlocks"}
	
  root "pages#welcome"
  get 'sales/filter/:scope', to: "sales#index", as: :filtered_sales
  get 'bids/filter/:scope', to: "bids#index", as: :filtered_bids
  get "welcome", to: "pages#welcome", as: 'welcome'
  get "about", to: "pages#about", as: 'about'
  get "buyers/bidding/:id/:sale", to: "buyers#bidding", as: :buyer_bidding

  resources :bids
  resources :buyers
  resources :houses
  resources :sellers
  resources :categories
  resources :auctioneers
  
  resources :sales do
    member do
      post :deactivate
      post :activate
    end
  end

  resources :lots do
    member do
      delete :delete_pictures
      delete :delete_image
      delete :delete_main_image
      post :reset_bids_and_fees
    end
  end

  delete "lots/:id/:image_id", to: 'lots#delete_one_attached_picture', as: :delete_one_attached_picture
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # and :omniauthable
  devise :database_authenticatable, :confirmable, :lockable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :lots

	validates :firstname, presence: true,
											  format: { with: /\A[a-z\s]+\Z/i, message: "only letters" },
                        length: { minimum: 1}

	validates :lastname, 	presence: true,
											  format: { with: /\A[a-z\s]+\Z/i, message: "only letters" },
												length: { minimum: 1 }

  validates :email, 		presence: true,
                    		format: /\A\S+@\S+\z/,
                    		uniqueness: { case_sensitive: false ,
                    									message: "Email address already in use"}

  # validates :phone,     numericality:  {message: "just digits no spaces"},
  # 											length: {minimum: 10, maximum: 14}

  # validates :code, 			presence: true

	validates_numericality_of :commrate, presence: true,
														greater_than_or_equal_to: 0

	scope :by_code, ->{order(code: :asc)}
	scope :lastname_firstname, ->{order(lastname: :asc).order(firstname: :asc)}

	def password_required?
	  false
	end

	def email_required?
	  true
	end

	def full_name
		"#{firstname} #{lastname}"
	end

	def eldest
		lots.order(created_at: :asc).first.sale.date unless lots.empty?
	end

	def code_and_name
		"#{code} (#{firstname} #{lastname})"
	end
end

app/controllers/sellers/confirmations_controller.rb
# frozen_string_literal: true

class Sellers::ConfirmationsController < Devise::ConfirmationsController
  include Accessible
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/sellers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Sellers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/sellers/passwords_controller.rb
# frozen_string_literal: true

class Sellers::PasswordsController < Devise::PasswordsController
  include Accessible
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/sellers/registrations_controller.rb
# frozen_string_literal: true

class Sellers::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sellers/sessions_controller.rb
# frozen_string_literal: true

class Sellers::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/sellers/unlocks_controller.rb
# frozen_string_literal: true

class Sellers::UnlocksController < Devise::UnlocksController
  include Accessible
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

	before_action :check_if_seller_or_admin, only:[:show]
	before_action :check_if_admin, except:[:show]


	def index
		@sellers = Seller.lastname_firstname.page(params[:page]).per(20)
	end

	def show
		@seller = Seller.find(params[:id])
		@active_lots = @seller.lots.select{| l | l.sold.nil? }.sort{|a,b| b.lotnumber<=> a.lotnumber}.sort{|a,b| b.sale.date <=> a.sale.date}
		@sold_lots = @seller.lots.select{| l | l.sold == true && l.dispute == false }.sort{|a,b| b.sale.date <=> a.sale.date}
		@paid_lots = @seller.lots.select{| l | l.sold == true && l.sellerpaid == true && l.dispute == false }.sort{|a,b| b.sale.date <=> a.sale.date}
		@unpaid_lots = @seller.lots.select{| l | l.sold == true && l.sellerpaid == false && l.dispute == false }.sort{|a,b| b.sale.date <=> a.sale.date}
		@unsold_lots = @seller.lots.select{| l | l.sold == false  && l.sellerpaid == false && l.dispute == false }.sort{|a,b| b.sale.date <=> a.sale.date}
		@disputed_lots = @seller.lots.select{| l | l.dispute == true }.sort{|a,b| b.sale.date <=> a.sale.date}
		@cash_made_by_seller = @paid_lots.sum{| l | (l.seller_due)} # lots paid
		@cash_due_to_seller = @unpaid_lots.sum{| l | (l.seller_due)}
		@total_lots_sold_by_seller = @sold_lots.count
		@since = @seller.eldest
		respond_to do |format|
			format.html
		  format.pdf do
		    render pdf: "Credit_Note-#{Time.now.to_date}-#{@seller.full_name.parameterize}",  header: { right: '[page] of [topage]' },
		           template: "sellers/creditnote.pdf.erb",
		           locals: {:seller => @seller}
		  end
		end
	end

	def new
		@seller = Seller.new
	end

	def create
		@seller = Seller.new(seller_params)
		if @seller.save
		  redirect_to @seller, notice: "#{@seller.full_name} created!"
		else
		  render :new
		end
	end

	def edit
		@seller = Seller.find(params[:id])
	end

	def update
		@seller = Seller.find(params[:id])
		if @seller.update(seller_params)
		  redirect_to @seller, notice: "#{@seller.full_name} updated!"
		else
		  render :edit
		end
	end

	def destroy
		@seller = Seller.find(params[:id])
		@seller.destroy
    redirect_to sellers_url, alert: "#{@seller.full_name} deleted!"
	end

	private

	def seller_params
		params.require(:seller).permit(:firstname, :lastname, :email, :phone, :commrate, :password, :code)
	end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_client_contact.html.erb
<div class="client-details">
	<table class='contact'>
		<tr>
			<td><i class="fas fa-phone"></i></td>
			<td><%= @seller.phone%></td>
		</tr>
		<tr>
			<td><i class="far fa-envelope"></i></td>
			<td><%= @seller.email%></td>
		</tr>
		<tr>
			<td><i class="fas fa-percent"></i></td>
			<td><%= @seller.commrate%></td>
		</tr>	
	</table>
</div>

app/views/sellers/_seller_facts.html.erb
<% unless @since.nil? %>
		<ul class='facts'>
			<li>Selling for <%= time_ago_in_words(@since)%>.</li>
			<li>Sold <%= @total_lots_sold_by_seller %>  of <%= pluralize(@seller.lots.count, 'lot')%>.</li>
			<li>Paid out to date <%=show_money(@cash_made_by_seller)%></li>
			<li>Credit Due <%= show_money(@cash_due_to_seller)%></li>
			<% unless @disputed_lots.empty? %>
				<li><%= pluralize(@disputed_lots.count, 'lot')%> in dispute.</li>
			<% end %>
			<% if @seller.last_sign_in_at%>
				<li>Last seen <%= time_ago_in_words(@seller.last_sign_in_at) %> ago.</li>
			<% end %>
		</ul>
<% end %>

app/views/sellers/creditnote.pdf.erb
<html>
	<head>
		<meta charset='utf-8' />
		<title>PDF</title>
		  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
	</head>
<body>
	<section class='title'>
		<h1>Account Statement</h1>
		<table class='summary'>
			<tr>
				<td>Date of issue</td><td class='money'><%= nice_date(Time.now)%></td>
			</tr>
			<tr>
				<td>Statement</td><td class='money'><%= @unpaid_lots.first.id %></td>
			</tr>
			<tr class='bold'>
				<td>Credit Due</td><td class='money'><%= show_money(@cash_due_to_seller)%></td>
			</tr>
		</table>
	</section>

	<section class='specifics'>
		<div class="billed">
			<h3><%= @seller.full_name %>,  <%= @seller.email if @seller.email %>,  <%= @seller.phone if @seller.phone %>.</h3>
			<% if @default %>
				<h3>with thanks : <%= @default.name%>.</h3>
				<p><%= @default.address1 if @default.address1 %>, <%= @default.address2 if @default.address2 %>, <%= @default.address3 if @default.address3 %>, <%= @default.postcode if @default.postcode %>, <%= @default.email if @default.email %>, <%= @default.phone if @default.phone %>.</p>
			<% end %>
		</div>
	</section>

	<section class="accounts">
		<table class='lots'>
		<div class="sold">
			<tr>
				<th colspan="7" class='header'>Lots Sold.</th>
			</tr>
			<tr class='bold'>
				<td>Date</td>
				<td>Auction</td>
				<td class='centre'>Lot</td>
				<td>Item</td>
				<td class="money">Selling Price</td>
				<td class="money">Selling Fees</td>
				<td class="money">Payment Due</td>
			</tr>
			<% @unpaid_lots.each do | lot| %>
				<tr>
					<td><%= short_date(lot.sale.date)%></td>
					<td><%= lot.sale.house.name %></td>
					<td class='centre'><%= lot.lotnumber%></td>
					<td><%= lot.make_and_model %></td>
					<td class="money"><%= show_money(lot.soldat)%></td>
					<td class="money"><%= show_money(lot.sfee)%></td>
					<td class="money"><%= show_money(lot.seller_due)%></td>
				</tr>
			<% end %>
			<tr></tr>
			<tr class='total'>
				<td colspan=6 class='money'>Total Credit Due</td>
				<td class='money'><%= show_money(@cash_due_to_seller)%></td>
			</tr>
		</div>
		<div class="unsold"></div>	
		<% unless @unsold_lots.empty? %>
			<tr>
				<th colspan="7" class='header'>Lots for collection.</th>
			</tr>
			<tr class='bold'>
				<td>Date</td>
				<td>Auction</td>
				<td class='centre'>Lot</td>
				<td>Item</td>
				<td class="money">Reserve</td>
				<td class="money">Bids</td>
				<td class='money'>Highest Bid</td>
			</tr>
			<% @unsold_lots.each do | lot| %>
			<tr>
				<td><%= short_date(lot.sale.date)%></td>
				<td><%= lot.sale.house.name%></td>
				<td><%= lot.lotnumber%></td>
				<td><%= lot.make_and_model%></td>
				<td class='money'><%= show_money(lot.reserve)%></td>
				<td class="money"><%= lot.bids.count%></td>
				<td class='money'><%= show_money(lot.highest_bid.first.bidvalue)%></td>
			</tr>
			<% end %>
		<% end %>
		</div>
		</table>
	</section>
	</body>
</html>

app/views/sellers/edit.html.erb
<article>
<header>
	<h1>Editing <%= @seller.full_name%></h1>
</header>
	<%= render "shared/errors", object: @seller %>
	<%= form_with(model:@seller, local:true) do |f| %>
		<%= render "shared/client_fields", f:f%>
		<%= f.submit %>
	<% end %>
</article>

<% content_for(:side_links) do %>
	<li class='contextual'>
		<%=link_to 'new seller', new_seller_path %>
	</li>	
<% end %>

app/views/sellers/index.html.erb
<article>
	<%= paginate @sellers %>
	<header>
		<h1>Clients - Sellers</h1>
	</header>
	
	<table>
		<% @sellers.each do |seller| %>
			<tr>
				<td class='hide'>(<%=seller.code%>)</td>
				<td><%=link_to "#{seller.full_name}", seller_path(seller) %></td>
				<td class='hide'><%=seller.email%></td>
				<td class='hide'><%=seller.phone%></td>
				<td>
					<% if seller.last_sign_in_at%>last seen <%= time_ago_in_words(seller.last_sign_in_at) %> ago.<% end %>
				</td>
				<td><%= link_to 'edit', edit_seller_path(seller)%></td>
				<td><%=link_to 'delete', seller, method: :delete, data: { confirm: 'Are you sure? There is no way back!' } if seller.lots.empty? %></td>
			</tr>
		<% end %>
	</table>
	<%= paginate @sellers %>
</article>

<% content_for(:side_links) do %>
	<li class='contextual'>
		<%=link_to 'new seller', new_seller_path %>
	</li>	
<% end %>

app/views/sellers/new.html.erb
<article>
	<header>
		<h1>Add a New Seller</h1>
	</header>
	<%= render "shared/errors", object: @seller %>
	<%= form_with(model: @seller, local: true) do |f| %>
		<%= render "shared/client_fields", f:f%>
		<%= f.submit %>
	<% end %>
</article>

<% content_for(:side_links) do %>
	<nav>
		<ul>
			<% unless controller.action_name == "index" %>
				<li>
					<%=link_to 'sellers list', sellers_path %>
				</li>
			<% end %>
		</ul>
	</nav>
<% end %>

app/views/sellers/show.html.erb
<article>
	<header>
		<h1><%= @seller.first_and_last_name %>
		<% unless @unpaid_lots.empty?%> (<%= link_to 'Statement', seller_path(@seller, :format => :pdf) %>)
		<% end %></h1>
	</header>
	<div class="details">
	<%= render "client_contact" %>
		<% if auctioneer_signed_in? %>
			<%= render "seller_facts" %>
		<% end %>
	</div>

		<% unless @active_lots.empty? %>
			<div class="live-items">
			<h3>Active Lots.</h3>
				<table>
					<tr>
						<td></td>
						<td class='hide'></td>
						<td class='hide'></td>
						<td></td>
						<td class='money'>Reserve</td>
						<td class='hide'></td>
						<td class='money'>Current Bidding</td>
					</tr>
					<% @active_lots.each do | lot| %>
						<tr>
							<td><%= short_date(lot.sale.date)%></td>
							<td class='hide'><%= lot.sale.house.code%></td>
							<td class='hide'><%= lot.lotnumber%></td>
							<td><%= lot.make_and_model %></td>
							<td class="money"><%= show_money(lot.reserve)%></td>
							<td class="money hide">(<%= pluralize(lot.bids.count, 'bid')%>)</td>
							<td class="money"><%= show_money(lot.selling_price)%></td>
						</tr>
					<% end %>
				</table>
			</div>
		<% end %>

		<% unless @unpaid_lots.empty? %>
			<div class="sold-lots">
				<h3>Sold lots due for payment.</h3>
				<table>
					<tr  class='highlight'>
						<td></td>
						<td></td>
						<td class= 'hide'></td>
						<td></td>
						<td class='hide'>Selling Price</td>
						<td class='hide'>Selling Fees</td>
						<td class="money">Amount Due</td>
						<% if auctioneer_signed_in? %>
							<td></td>
						<% end %>
					</tr>
					<% @unpaid_lots.each do | lot| %>
						<tr>
							<td><%= short_date(lot.sale.date)%></td>
							<td><%= lot.sale.house.code%></td>
							<td class= 'hide'><%= lot.lotnumber%></td>
							<td><%= lot.make_and_model %></td>
							<td class="money hide"><%= show_money(lot.soldat)%></td>
							<td class="money hide"><%= show_money(lot.sfee)%></td>
							<td class="money"><%= show_money(lot.seller_due)%></td>
							<% if auctioneer_signed_in? %>
								<td><%= link_to 'edit', edit_lot_path(lot)%></td>
							<% end %>
						</tr>
					<% end %>
					<tr></tr>
					<tr class='highlight'>
						<td class= 'hide'></td>
						<td class= 'hide'></td>
						<td class= 'hide'></td>
						<td colspan=3 class='right'>Total Credit Due</td>
						<td class='money'><%= show_money(@cash_due_to_seller)%></td>
					</tr>
				</table>
			</div>
		<% end %>

		<% unless @disputed_lots.empty? %>
			<div class="disputed-lots">
				<h3>Disputed Lots.</h3>
				<table>
					<% @disputed_lots.each do | lot| %>
						<tr>
							<td><%= short_date(lot.sale.date)%></td>
							<td><%= lot.sale.house.code%></td>
							<td class='hide'><%= lot.lotnumber%></td>
							<td><%= lot.make_and_model %></td>
						</tr>
					<% end %>
				</table>
			</div>
		<% end %>

		<% unless @unsold_lots.empty? %>
			<div class="unsold-lots">
				<h3>Unsold lots to be collected.</h3>
					<table>
						<tr>
							<td class='hide'>Date</td>
							<td class='hide'>Sale</td>
							<td class='hide'>Lot</td>
							<td>Item</td>
							<td>Reserve</td>
							<td class='hide'></td>
							<td>Highest Bid</td>
						</tr>
				</tr>
				<% @unsold_lots.each do | lot| %>
					<tr>
						<td class='hide'><%= short_date(lot.sale.date)%></td>
						<td class='hide'><%= lot.sale.house.code%></td>
						<td class='hide'><%= lot.lotnumber%></td>
						<td><%= link_to "#{lot.make_and_model}", lot_path(lot) %></td>
						<td class='money'><%= show_money(lot.reserve)%></td>
						<td class='hide'><%= pluralize(lot.bids.count, 'bid')%></td>
						<td class='money'><%= show_money(lot.highest_bid.first.bidvalue)%></td>
					</tr>
				<% end %>
			</div>
		<% end %>
	</table>
</article>
<% content_for(:side_links) do %>

		<li class='contextual'>
		<%=link_to 'edit this seller', edit_seller_path(@seller) %>
	</li>	
		<li class='contextual'>
		<%=link_to 'new seller', new_seller_path %>
	</li>
<% end %>