config/routes.rb
Rails.application.routes.draw do

  
  devise_for :sellers, path: 'sellers', controllers: { sessions: "sellers/sessions", confirmations: "sellers/confirmations", passwords: "sellers/passwords", unlocks: "sellers/unlocks"}
  devise_for :buyers, path: 'buyers', controllers: { sessions: "buyers/sessions", confirmations: "buyers/confirmations", passwords: "buyers/passwords", unlocks: "buyers/unlocks"}
  devise_for :auctioneers, path: 'auctioneers', controllers: { sessions: "auctioneers/sessions", confirmations: "auctioneers/confirmations", passwords: "auctioneers/passwords", unlocks: "auctioneers/unlocks"}
	
  root "pages#welcome"
  get 'sales/filter/:scope', to: "sales#index", as: :filtered_sales
  get 'bids/filter/:scope', to: "bids#index", as: :filtered_bids
  get "welcome", to: "pages#welcome", as: 'welcome'
  get "about", to: "pages#about", as: 'about'
  get "buyers/bidding/:id/:sale", to: "buyers#bidding", as: :buyer_bidding

  resources :bids
  resources :buyers
  resources :houses
  resources :sellers
  resources :categories
  resources :auctioneers
  
  resources :sales do
    member do
      post :deactivate
      post :activate
    end
  end

  resources :lots do
    member do
      delete :delete_pictures
      delete :delete_image
      delete :delete_main_image
      post :reset_bids_and_fees
    end
  end

  delete "lots/:id/:image_id", to: 'lots#delete_one_attached_picture', as: :delete_one_attached_picture
end

app/models/lot.rb
class Lot < ApplicationRecord
	belongs_to :sale
	belongs_to :category
	belongs_to :seller
	belongs_to :buyer, optional:true
	has_many :bids, dependent: :destroy
	has_many :bidders, through: :bids, source: :buyer
	has_one_attached :image
	has_many_attached :pictures

	validates :manufacturer, :description, :lotnumber, :model,
										presence: true
	validates_numericality_of :reserve,
										presence: true, greater_than_or_equal_to: 0

	scope :by_lot_number, ->{order(lotnumber: :asc)}
	scope :auctioned, ->{where(sold: [true,false]).joins(:sale).merge(Sale.descending)}
	scope :sold_in_auction, ->{where(sold: [true, false ]).count}

	def self.total_sales
		sum{|l| l.soldat}
	end

	def self.total_buyer_costs
		total_buyer_fees + total_sales
	end

	def self.total_buyer_fees
		sum{|l| l.bfee}
	end

	def self.total_seller_fees
		sum{|l| l.sfee}
	end

	def self.total_comm
		total_buyer_fees + total_seller_fees
	end

	def self.total_gross
		total_sales + total_buyer_fees
	end

	def self.pay_out
		total_sales - total_seller_fees
	end

	def self.average_profit
		if self.count == 0
			0
		else
			total_comm / self.count
		end
	end

	def self.average_bid
		if self.count == 0
			0
		else
			total_sales / self.count
		end
	end


	def sale_date
		sale.date
	end

	def sale_name
		sale.house.code
	end


	def self.to_csv
		CSV.generate do |csv|
			csv << ["Date", "Sale", "Lot#", "Lot_id", "Item", "Reserve", "Sold", "Highest bid", "Selling Price", "Profit", "Buyer", "Buyer Fee", "Buyer Charge","Buyer Paid", "Seller", "Seller Fee", "Seller Due", "Seller Paid"]
			all.each do |lot|
					row = [lot.sale_date, lot.sale_name, lot.lotnumber, lot.id, lot.make_and_model, lot.reserve, lot.sold, lot.highest_bid_value, lot.soldat, lot.commissions, lot.buyers_name, lot.bfee, (lot.bfee + lot.soldat), lot.buyerpaid, lot.seller.full_name, lot.sfee, lot.seller_due,lot.sellerpaid ]
					csv << row
			end
		end
	end


# call this after it's all sorted out
	def winning_bid
			bids.where(won:true).first
	end

	def winning_bid_buyer_name
		if winning_bid.nil?
			"no sale"
		else
			bids.where(won:true).first.buyer.full_name
		end
	end

	def make_and_model
		"#{manufacturer} #{model}"
	end

	def buyer_pays
		bfee + soldat
	end

	def seller_due
		soldat - sfee
	end

	def sellingfee
		if selling_price == 0
			0
		else
			sale.minfee >= ((selling_price/100) * seller.commrate) ? sale.minfee : ((selling_price/100) * seller.commrate)
		end
	end

	def buyingfee
		if selling_price == 0
			0
		else
			sale.minfee >= ((selling_price/100) * highest_bid.first.buyer.commrate) ? sale.minfee : ((selling_price/100) * highest_bid.first.buyer.commrate)
		end
	end

	def commissions
		if sold?
			bfee + sfee
		else
			0
		end
	end

	def reset
		self.update_attributes(soldat:nil, bfee:nil, sfee:nil, sold:nil, buyerpaid:nil, sellerpaid:nil, buyer_id:nil, dispute:false)
		self.bids.destroy_all
	end

	def buyer_highest_bid(buyer)
		bids.where("buyer_id = ?", buyer).order(bidvalue: :desc).first
	end

	def highest_bid
		bids.order(bidvalue: :desc)
	end

	def highest_bid_value
		if highest_bid.empty?
			0
		else
			highest_bid.first.bidvalue
		end
	end

	def buyers_name
		self.buyer_id.nil? ? 'no sale' : buyer.full_name
	end

# is there a bid on the lot from another buyer?
	def second_best_bid?
		!second_best_bid.nil?
	end

# get the highest bid from a different buyer
	def second_best_bid
		if bidders.uniq.size <= 1
			# no buyers
			nil
		else
			bids.where.not(buyer_id: highest_bid.first.buyer.id).order(bidvalue: :desc).first
		end
	end

	def selling_price
		if bids.size < 1
			# if no bids.....
			0
		else
			if self.second_best_bid?
				# selling price is second bid from different buyer plus notch (if there is a 2nd bid)
				(self.sale.notch + self.second_best_bid.bidvalue)
			else
				if self.highest_bid_value >= self.reserve
					# else if highest bid is equal or greater then reserve add notch to reserve
					(self.sale.notch + self.reserve)
				else
					# else add notch to highest bid as less than reserve
					(self.sale.notch + self.highest_bid_value)
				end
			end
		end
	end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController

	before_action :auctioneer_or_buyer_logged_in, only: [:show]
	before_action :check_if_admin, except:[:show]

	def index
		session[:q] = params[:q] if params[:q]
		search
		
		items if search_params

		@saved_for_csv = Lot.auctioned.search(session[:q]).result

		respond_to do |format|
			format.html
			format.csv { send_data @saved_for_csv.to_csv }
		end
		
	end

	def show
		@lot = Lot.find(params[:id])
	end

	def edit
		@lot = Lot.find(params[:id])
	end

	def update
	@lot = Lot.find(params[:id])
		if @lot.update(lot_params)
		  redirect_to lots_url notice: "Lot successfully updated!"
		else
		  render :edit
		end
	end

	def destroy
		@lot = Lot.find(params[:id])
		@lot.destroy
    redirect_to sales_path, alert: "Lot successfully deleted!"
	end

	def delete_image
		@lot = Lot.find(params[:id])
		@lot.image.purge
		redirect_to edit_sale_url(@lot.sale)
	end

	def delete_pictures
		@lot = Lot.find(params[:id])
		@lot.pictures.purge
		redirect_to edit_sale_url(@lot.sale)
	end

	def delete_one_attached_picture
		@lot = Lot.find(params[:id])
		@lot.pictures.find(params[:image_id]).purge
		redirect_to edit_lot_url(@lot), alert: "Image deleted"
	end

	def delete_main_image
		@lot = Lot.find(params[:id])
		@lot.image.purge
		redirect_to request.referrer, alert: "Image deleted"
	end

	def reset_bids_and_fees
		@lot = Lot.find(params[:id])
		flash[:alert] = "All bids destroyed, all fees reset" if @lot.reset
		redirect_to edit_lot_url(@lot)
	end

	private

	def items
	  @lots ||= search.result
	  # add .page(params[:page]).per(20) to above to paginate...
	end 

	def search
		@search ||= Lot.all.search(search_params)
	end

	def search_params
		params[:q]
	end

	def lot_params
		params.require(:lot).permit(:sale_id, :manufacturer, :model, :description, :lotnumber, :reserve, :dispute, :category_id, :buyer_id, :seller_id, :winner, :soldat, :bfee, :sfee, :sold, :buyerpaid, :sellerpaid, :image, pictures:[])
	end
end

app/helpers/lots_helper.rb
module LotsHelper


end

app/views/lots/_bid_field.html.erb
<fieldset class='bid-form'>
	<div class="current-bidding-info">
		<h3><%= show_money(@lot.selling_price)%> (<%= pluralize(@lot.bids.count, 'bid')%>)</h3>
		<% unless @lot.selling_price >= @lot.reserve %>
			<h3>Reserve not met</h3>
		<% end %>
	</div>
	<div class="actions">
		<%= form_with(model: Bid.new, url: bids_path, method: :post, local:true) do |f| %>	
	  	<%=f.hidden_field :lot_id , value: @lot.id %>
	  	<div class="bid-maker">
	  		<div class="number-maker">
		  		<%=f.number_field :bidvalue %>
		  	</div>
		  	<div class="sender-maker">
		    	<%=f.submit "Bid", data: { confirm: 'Bids cannot be retracted, Are you sure ?' }%>
		    </div>
	    </div>
		<% end %>
	</div>
</fieldset>

app/views/lots/_lot_fields.html.erb
<fieldset class='lot-edit'>
	<ul>
		<% if @lot.bids.blank? && (@lot.sold == nil || false) %>
			<div class="details">
				<li>
					<h3>Lot <%= @lot.lotnumber %><%if @lot.sale %>, <%= @lot.sale.house.name %> <%= short_date(@lot.sale.date) %><% end %></h3>
					<h4>(record id <%= @lot.id %>)</h4>
				</li>
				<li>
					<label>Change Auction</label>
					<%= f.collection_select(:sale_id, Sale.process, :id, :code_and_date, prompt: 'All Sales')%>
				</li>
				<li>
					<label class='next'>Lot Number</label>
					<%=f.number_field :lotnumber, step: 0.01 %>
				</li>
				<li>
					<label class='next'>Category</label>
					<%= f.collection_select(:category_id, Category.alpha, :id , :title, prompt: "Choose Category" ) %>
				</li>
				<li>
					<label class='next'>Seller</label>
					<%= f.collection_select(:seller_id, Seller.by_code, :id , :code_and_name, prompt: "Choose Seller" ) %>
				</li>
				<li>
					<label class='next'>Manufacturer</label>
					<%=f.text_field :manufacturer%>
				</li>
				<li>
					<label class='next'>Model</label>
					<%=f.text_field :model%>
				</li>
				<li>
					<label class='next'>Reserve</label>
					<%=f.number_field :reserve, step: 0.01 %>
				</li>
				<li>
					<label class='next'>Description</label>
					<%=f.text_area :description , rows: 10 %>
				</li>
			</div>
			<!-- main image -->
			<li class='image'>
				<% if f.object.image.attached? %>
						<label>Main Image</label>
						<div class="image-block">
							<div class='block-image'>
								<%= image_tag f.object.image.variant(resize: "200x")%>
								<p><%= link_to 'delete', delete_main_image_lot_url(f.object.id), 
										 	method: :delete, data: { confirm: 'Are you sure? No way back!' } %></p>
								<label>Change Image</label><%=f.file_field :image%>
							</div>
						</div>
				<% else %>
					<label>Main Image</label>
					<%=f.file_field :image%>
				<% end %>
			</li>
			<li>
				<% if f.object.pictures.attached? %>
					<label>Additional Images</label>
						<div class="picture-gallery">
							<% f.object.pictures.each do |picture | %>
								<div class="lot-picture">
									<%= image_tag picture.variant(resize: "100x")%>
									<p></p>
									<p><%= link_to 'delete', delete_one_attached_picture_path(@lot, picture.id), 
											 	method: :delete, data: { confirm: 'Are you sure? No way back!' } %></p>
								</div>
							<% end %>
						</div>
					<label>Add More Images</label>
					<%=f.file_field :pictures, multiple: true%>
				<% else %>
					<label>Additional Images</label>
					<%=f.file_field :pictures, multiple: true%>
				<% end %>
			</li>

		<!-- there are bids involved lot may or not gone through auction -->
	
		<% else %>





			<div class="details">
				<li>
					<h3>Lot <%= @lot.lotnumber %><%if @lot.sale %>, <%= @lot.sale.house.name %> <%= short_date(@lot.sale.date) %><% end %></h3>
					<h4>(record id <%= @lot.id %>)</h4>
				</li>
				<li>
				<% if @lot.sold.nil? %>
					<h4>(Lot with bids)</h4>
				<% else %>
					<h4>(Auction closed)</h4>
				<% end %>
				</li>
				<% if @lot.sold.nil? %>
						<li>
							<%= pluralize(@lot.bids.count, 'bid')%>, <%= pluralize(@lot.bidders.uniq.count, 'bidder')%>
						</li>
						<li>
							Reserve: <%= show_money(@lot.reserve)%>
						</li>
						<li>
							High Bid: <%= show_money(@lot.highest_bid_value) %>
						</li>
					</div>
				<% else %>
						<li>
							<label>Sold at £</label>
							<%= f.number_field :soldat, step: 0.01 %>
						</li>
						<li>
							<label>Sold</label>
							<%= f.check_box :sold%>
						</li>
					</div>

					<div class="seller">
						<li>
							<label>Seller</label>
							<%= f.collection_select(:seller_id, Seller.by_code, :id , :code_and_name, prompt: "Choose Seller" ) %>
						</li>
						<li>
							<label>Seller fee £</label>
							<%= f.number_field :sfee, step: 0.01 %>
						</li>
						<% unless @lot.sold.nil? %> 
							<li class='amount'>
								Seller Due : <%=show_money(@lot.seller_due)%>
							</li>
						<% end %>
						<li>
							<label>Seller paid</label>
							<%= f.check_box :sellerpaid%>
						</li>
					</div>

					<div class="buyer">
						<li>
							<label>Buyer</label>
							<%= f.collection_select(:buyer_id, Buyer.all, :id , :code_and_name, include_blank: true) %>
						</li>
						<li>
							<label>Buyer fee £</label>
							<%= f.number_field :bfee, step: 0.01 %>
						</li>
						<% unless @lot.sold.nil? %> 
							<li class='amount'>
								Buyer Pays : <%=show_money(@lot.buyer_pays)%>
							</li>
						<% end %>
						<li>
							<label>Buyer paid</label>
							<%= f.check_box :buyerpaid%>
						</li>
					</div>

					<div class="dispute">
						<li>
							<label>In Dispute ?</label>
							<%= f.check_box :dispute%>
						</li>
					</div>
				<% end %>
			<% end %>

			<% unless @lot.bids.empty? && @lot.sold.nil? %>
				<div class="kill-bids">
					<li>
						<%= link_to 'withdraw & reset?', reset_bids_and_fees_lot_path(@lot.id), method: :post,
													          data: { confirm: "Are you sure? You will need a new sale, (open or lotting up), for this lot to go into, if you haven't made one yet come back when you have. This will destroy all bidding and financial details so the lot can be resold, there is no way back. The images, seller and item details will all be retained." } %>
					</li>
				</div>
			<% end %>

		</ul>

	
</fieldset>
		

app/views/lots/_lot_search_form.html.erb
<div class="lot-search">
	<fieldset class='lot-search'>
	  <%= search_form_for @search do |f| %>
	  <table>
	  	<tr>
	  		<td>Auction</td>
	  		<td><%= f.collection_select(:sale_id_eq, Sale.all, :id, :code_and_date, prompt: 'All Sales', include_blank: true )%></td>
	  		<td><%= f.select :sold_eq, options_for_select([["All lots", ""],["Sold lots", "true"], ["Failed to sell", "false"]])%></td>
	  		<td><%= f.collection_select(:category_id_eq, Category.all, :id, :title, prompt: 'All Categories', include_blank: true )%></td>
	  		<td><%= f.number_field :lotnumber_or_id_eq, placeholder: 'Lot or ID number...'%></td>
	  	</tr>
	  	<tr>
	  		<td>Seller</td>
	  		<td><%= f.collection_select(:seller_id_eq, Seller.lastname_firstname, :id , :code_and_name, prompt: "All Sellers", include_blank: true  ) %></td>
	  		<td><%= f.select :sellerpaid_eq, options_for_select([["Paid & Due", ""],["Paid", "true"], ["Seller Owed", "false"]])%></td>
	  		<td></td>
	  		<td><%= f.text_field :manufacturer_or_model_or_description_cont, placeholder: 'Search in items for...'%></td>
	  	</tr>
	  	<tr>
	  		<td>Buyer</td>
	  		<td><%= f.collection_select(:buyer_id_eq, Buyer.lastname_firstname, :id , :code_and_name, prompt: "All Buyers", include_blank: true  ) %></td>
	  		<td><%= f.select :buyerpaid_eq, options_for_select([["Paid & Due", ""],["Paid", "true"], ["Buyer Owes", "false"]])%></td>
	  		<td><%= f.select :dispute_eq, options_for_select([["No dispute filter", ""],["Disputed", "true"], ["Undisputed", "false"]])%></td>
	  		<td><%= f.submit "Search" %></td>
	  	</tr>
	  </table>
		<% end %>
	</fieldset>
</div>

app/views/lots/_side_stats.html.erb
		<div class="side-stats">
			<table>
				</tr>
					<tr>
					<td>Lots</td>
					<td class='money'><%= @how_many%></td>
				</tr>
					<tr>
					<td>Bids</td>
					<td class='money'><%=show_money(@total_sales)%></td>
				</tr>
				<tr>
					<td>Turnover</td>
					<td class='money'><%=show_money(@gross)%></td>
				</tr>
				<tr>
					<td>Seller's due</td>
					<td class='money'><%=show_money(@pay_out)%></td>
				</tr>
					<tr>
					<td>Seller fees</td>
					<td class='money'><%=show_money(@seller_fees)%></td>
				</tr>
					<tr>
					<td>Buyer fees</td>
					<td class='money'><%=show_money(@buyer_fees)%></td>
				</tr>
					<tr>
					<td>Profit</td>
					<td class='money'><%=show_money(@comm)%></td>
				</tr>
				<tr>
					<td>Av. bid</td>
					<td class='money'><%=show_money(@average_bid)%></td>
				</tr>
				<tr>
					<td>Av. profit/lot</td>
					<td class='money'><%=show_money(@average)%></td>
				</tr>
			</table>
		</div>

app/views/lots/edit.html.erb
<article>
	<header>
		<h1>Editing <%= @lot.manufacturer%> <%= @lot.model%></h1>
	</header>
	<%= render "shared/errors", object: @lot %>
	<%= form_with(model: @lot, local:true) do |f| %>
		<%= render 'lot_fields', f: f%>
		<%= f.submit %>
	<% end %>
</article>

app/views/lots/index.html.erb
<article>
	<header>
		<h1 class='desktop'>Use the filters above to search and edit lots.</h1>
		<h1 class='mobile'>Turn to landscape to search and edit sold lots.</h1>
		<%= render 'lot_search_form' %>
	</header>
	
	<%if @lots.nil?%>
		<h4 class='desktop'>Use the filters above to search and edit lots.</h4>
	<% else %>
		<% if @lots.empty? %>
			<h4>No search results, no lots fit the criteria.</h4>
		<% else %>
	
			<table class='all-lots'>
				<tr class='highlight'>
					<td>Date</td>
					<td>Sale</td>
					<td>Lot</td>
					<td>Item</td>
					<td class='money'>Reserve</td>
					<td class='money'>Sold @</td>
					<td class='money'>Fee (Buyer)</td>
					<td class='money'>Fee (Seller)</td>
					<td class='money'>Fee (Total)</td>
					<td></td>
				</tr>
				<% @lots.each do |lot| %>
				<tr>
					<td><%= short_date(lot.sale_date) %></td>
					<td><%= lot.sale_name %></td>
					<td class='money'><%= lot.lotnumber %></td>
					<td><%= link_to truncate(lot.make_and_model, length:16, separator: " "), lot_path(lot) %></td>
					<td class='money'><%= show_money(lot.reserve)%></td>
					<td class='money'><%= show_money(lot.soldat) %></td>
					<td class='money'><%= show_money(lot.bfee) %></td>
					<td class='money'><%= show_money(lot.sfee) %></td>
					<td class='money'><%= show_money(lot.commissions) %></td>
					<td><%=link_to 'edit', edit_lot_path(lot)%></td>
					<td></td>
				</tr>
				<% end %>
			</table>

		<% end %>
	<% end %>
</article>

<!-- content_for side_stats removed render side-stats -->


<% content_for(:side_links) do %>
	<li>
			<%= link_to 'download CSV', lots_path(format: "csv") %>
	</li>
<% end %>

app/views/lots/show.html.erb
<article>
	<header>
		<h1>Lot <%=@lot.lotnumber%> - <%=nice_date(@lot.sale.date)%></h1>
		<h2><%=@lot.sale.house.name%>.</h2>
	</header>
	<div class="top-box">
		<div class="title-image">
			<%= image_tag @lot.image.variant(resize: '200x') if @lot.image.attached? %>
		</div>
		<div class="title-for-bid">
			<div class="item">
				<h2><%= @lot.model %></h2>
				<h3><%= @lot.manufacturer %></h3>
			</div>
			<div class="bid">
				<% if @lot.sale.complete? %>
					<% if @lot.selling_price >= @lot.reserve %>
						<h3>Sold at : <%= show_money(@lot.selling_price)%></h3>
					<% else %>
						<h3>Reserve not met</h3>
					<% end %>
				<% else %>
					<% if buyer_signed_in? %>
						<% if @lot.sale.active? %>
							<%= render 'lots/bid_field'%>
						<% end %>
					<% end %>
				<% end %>

				<% if current_seller %>
					<p><%= link_to 'back to account', seller_path(current_seller)%></p>
				<% end %>
			</div>
		</div>
	</div>
	<%= render 'shared/lot_item', lot: @lot%>
	<% if current_buyer %>
		<div class="buyer-account">
			<%= link_to 'back to bidding card', buyer_bidding_path(current_buyer.id, @lot.sale.id)%>
		</div>
	<% end %>
	<% if auctioneer_signed_in?%>
		<% content_for(:side_links) do %>
			<li class='contextual'>
				<%=link_to 'edit this lot', edit_lot_path(@lot) %>
			</li>	
		<% end %>
	<% end %>
</article>