config/routes.rb
Rails.application.routes.draw do

  
  devise_for :sellers, path: 'sellers', controllers: { sessions: "sellers/sessions", confirmations: "sellers/confirmations", passwords: "sellers/passwords", unlocks: "sellers/unlocks"}
  devise_for :buyers, path: 'buyers', controllers: { sessions: "buyers/sessions", confirmations: "buyers/confirmations", passwords: "buyers/passwords", unlocks: "buyers/unlocks"}
  devise_for :auctioneers, path: 'auctioneers', controllers: { sessions: "auctioneers/sessions", confirmations: "auctioneers/confirmations", passwords: "auctioneers/passwords", unlocks: "auctioneers/unlocks"}
	
  root "pages#welcome"
  get 'sales/filter/:scope', to: "sales#index", as: :filtered_sales
  get 'bids/filter/:scope', to: "bids#index", as: :filtered_bids
  get "welcome", to: "pages#welcome", as: 'welcome'
  get "about", to: "pages#about", as: 'about'
  get "buyers/bidding/:id/:sale", to: "buyers#bidding", as: :buyer_bidding

  resources :bids
  resources :buyers
  resources :houses
  resources :sellers
  resources :categories
  resources :auctioneers
  
  resources :sales do
    member do
      post :deactivate
      post :activate
    end
  end

  resources :lots do
    member do
      delete :delete_pictures
      delete :delete_image
      delete :delete_main_image
      post :reset_bids_and_fees
    end
  end

  delete "lots/:id/:image_id", to: 'lots#delete_one_attached_picture', as: :delete_one_attached_picture
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :lots

	validates :title, presence: true

	scope :type, ->(id){where('id = ?', id)}
	scope :alpha, ->{order( title: :asc)}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :check_if_admin

		def index
			@categories = Category.alpha
		end

		def show
			@category = Category.find(params[:id])
		end

		def new
			@category = Category.new
		end

		def create
			@category = Category.new(category_params)
			if @category.save
			  redirect_to categories_path, notice: "#{@category.title} successfully created!"
			else
			  render :new
			end
		end

		def edit
			@category = Category.find(params[:id])
		end

		def update
			@category = Category.find(params[:id])
			if @category.update(category_params)
			  redirect_to categories_path, notice: "#{@category.title} successfully updated!"
			else
			  render :edit
			end
		end

		def destroy
			@category = Category.find(params[:id])
			@category.destroy
	    redirect_to categories_path, alert: "#{@category.title} successfully deleted!"
		end

		private

		def category_params
			params.require(:category).permit(:title, :id)
		end
	end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_fields.html.erb
<fieldset>
	<ul>
		<li>
			<label>Title</label>
			<%= f.text_field :title%>
		</li>
	</ul>
</fieldset>

app/views/categories/edit.html.erb
<article>
	<header>
		<h1>Edit <%=@category.title%></h1>
	</header>
	<%= render 'shared/errors', object: @category %>
	<%=form_with(model:@category, local:true) do |f| %>
		<%= render 'category_fields', f:f %>
		<%= f.submit %>
	<% end %>
</article>

<% content_for(:side_links) do %>
	<li class='contextual'>
		<%=link_to 'add category', new_category_path %>
	</li>	
<% end %>

app/views/categories/index.html.erb
<article>
	<header>
		<h1>Auction Categories</h1>
	</header>
	<table>
		<% @categories.each do |category| %>
		<tr>
			<td><%= category.title %></td>
			<td><%=link_to 'edit', edit_category_path(category) %></td>
		</tr>
		<% end %>
	</table>
</article>

<% content_for(:side_links) do %>
	<li class='contextual'>
		<%=link_to 'add category', new_category_path %>
	</li>	
<% end %>

app/views/categories/new.html.erb
<article>
	<header>
		<h1>Add a new Category</h1>
	</header>
	<%= render 'shared/errors', object: @category %>
	<%=form_with(model:@category, local:true) do |f| %>
		<%= render 'category_fields', f:f %>
		<%= f.submit %>
	<% end %>
</article>