config/routes.rb
Rails.application.routes.draw do

  
  devise_for :sellers, path: 'sellers', controllers: { sessions: "sellers/sessions", confirmations: "sellers/confirmations", passwords: "sellers/passwords", unlocks: "sellers/unlocks"}
  devise_for :buyers, path: 'buyers', controllers: { sessions: "buyers/sessions", confirmations: "buyers/confirmations", passwords: "buyers/passwords", unlocks: "buyers/unlocks"}
  devise_for :auctioneers, path: 'auctioneers', controllers: { sessions: "auctioneers/sessions", confirmations: "auctioneers/confirmations", passwords: "auctioneers/passwords", unlocks: "auctioneers/unlocks"}
	
  root "pages#welcome"
  get 'sales/filter/:scope', to: "sales#index", as: :filtered_sales
  get 'bids/filter/:scope', to: "bids#index", as: :filtered_bids
  get "welcome", to: "pages#welcome", as: 'welcome'
  get "about", to: "pages#about", as: 'about'
  get "buyers/bidding/:id/:sale", to: "buyers#bidding", as: :buyer_bidding

  resources :bids
  resources :buyers
  resources :houses
  resources :sellers
  resources :categories
  resources :auctioneers
  
  resources :sales do
    member do
      post :deactivate
      post :activate
    end
  end

  resources :lots do
    member do
      delete :delete_pictures
      delete :delete_image
      delete :delete_main_image
      post :reset_bids_and_fees
    end
  end

  delete "lots/:id/:image_id", to: 'lots#delete_one_attached_picture', as: :delete_one_attached_picture
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :house
  has_many :lots, dependent: :destroy
  has_many :vendors, through: :lots, source: :seller
  has_many :bids, dependent: :destroy
  has_many :bidders, through: :bids, source: :buyer
  accepts_nested_attributes_for :lots, allow_destroy: true, reject_if: ->(attrs) { attrs['lotnumber'].blank? || attrs['description'].blank? || attrs['reserve'].blank? || attrs['manufacturer'].blank? }

  validates :date, presence: true
  validates_numericality_of :notch, :minfee, presence: true, greater_than_or_equal_to: 0

  scope :descending, ->{order(date: :desc)}
  scope :live, ->{descending.where('active = ?', true)}
  scope :ended, ->{descending.where('complete = ?', true)}
  scope :process, ->{descending.where('complete = ?', false)}
  scope :previous, ->{ended.order(date: :desc)}
  scope :just_ended, ->{ended.order(date: :desc).first}
  scope :building, ->{where('active = ? AND complete = ? ', false, false)}

  def ordered_bidders
    bidders.uniq.sort{|a,b| a.lastname <=> b.lastname}
  end

  def live_lots_asc
   lots.sort{| b,a| b.lotnumber <=> a.lotnumber}
  end

  def house_and_date
  	"#{house.name} #{nice_date(date)}"
  end

  def code_and_date
    "#{house.code} #{short_date(date)}"
  end

  def active?
  	active == true
  end

  def complete?
    complete == true
  end

  def frozen?
    complete? || active? == true
  end

  def building?
    complete? && active? == false
  end

  def activate
    update_attributes(active: true, complete: false)
  end

  def deactivate
    update_attributes(active: false, complete: true)
  end

  def write_auction_info_to_lots!
    lots.each do |lot|
      if lot.reserve > lot.highest_bid_value
        lot.update_attributes(sold: false, soldat: 0, bfee:0, sfee:0) # not setting buyer/sellerpaid to true as these attributes decide lot populating on show page of relevant nodel
      else
        lot.update_attributes(soldat:lot.selling_price, bfee:lot.buyingfee, sfee:lot.sellingfee, sold: true, buyerpaid:false, sellerpaid:false, buyer_id:lot.highest_bid.first.buyer_id)
        lot.highest_bid.first.update(won: true)
      end
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	before_action :auctioneer_or_buyer_logged_in, only: [:show]
	before_action :check_if_admin, except:[:show]

		def index
			@sales  = Sale.send(sales_scope).page(params[:page]).per(10)
			@building = @sales.building
			@live_sales = @sales.live
			@complete_sales = @sales.ended
		end

		def show
			@sale = Sale.find(params[:id])
			@lots = @sale.lots.by_lot_number
		end

		def new
			@sale = Sale.new
		end

		def create
			@sale = Sale.new(sale_params)
			if @sale.save
			  redirect_to @sale, notice: "#{@sale.house.name} #{nice_date(@sale.date)} created!"
			else
			  render :new
			end
		end

		def edit
			@sale = Sale.find(params[:id])
		end

		def update
			@sale = Sale.find(params[:id])
			if @sale.update(sale_params)
			  redirect_to @sale, notice: "#{@sale.house.name} #{nice_date(@sale.date)} updated!"
			else
			  render :edit
			end
		end

		def destroy
			@sale = Sale.find(params[:id])
			if @sale.bids.empty?
				@sale.destroy
		    redirect_to sales_url, alert: "#{@sale.house.name} #{nice_date(@sale.date)} and all lots deleted!"
		  else
		  	redirect_to @sale, alert: "#{@sale.house.name} #{nice_date(@sale.date)} cannot be deleted as bids have been made!"
		  end
		end

		def activate
			@sale = Sale.find(params[:id])
		  flash[:notice] = "It's on - #{@sale.house.name} #{nice_date(@sale.date)} Active." if @sale.activate
		  redirect_to sales_url
		end

		def deactivate
			@sale = Sale.find(params[:id])
		  flash.now[:notice] = "#{@sale.house.name} #{nice_date(@sale.date)} building report..." if @sale.deactivate
		  @sale.write_auction_info_to_lots!
		  flash[:notice] = "#{@sale.house.name} #{nice_date(@sale.date)} now closed - report built."
		  redirect_to sales_url
		end


		private

		def sales_scope
		  if params[:scope].in? %w(ended building live)
		    params[:scope]
		  else
		    :live
		  end
		end

		def set_sale
			@sale = Sale.find(params[:id])
		end

		def sale_params
			params.require(:sale).permit(:notch, :minfee, :date, :house_id,
			lots_attributes:[ :id, :_destroy, :category_id, :seller_id, :manufacturer, :model, :description, :lotnumber, :reserve, :image, pictures:[] ])
		end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_contextual_menu.html.erb
<% if controller.action_name == "show" %>
	<% if !@sale.frozen? %>
			<li class='contextual'>
				<%= link_to 'edit this sale', edit_sale_path(@sale) unless @sale.frozen? %>
			</li>
	<% end %>
<% end %>

<% unless controller.action_name == "new" %>
	<li class='contextual'>
		<%=link_to 'create a new sale', new_sale_path %>
	</li>
<% end %>

<% if controller.action_name == "index" %>
		<li>
			<%= link_to	'lotting up....', filtered_sales_path(:building)%>
		</li>
		<li>
			<%= link_to	'live auctions', filtered_sales_path(:active)%>
		</li>
		<li>
			<%= link_to	'completed auctions', filtered_sales_path(:ended)%>
		</li>
<% end %>
<li>
	<%= link_to 'sale categories', categories_path %>
</li>
<li>
	<%= link_to 'auction houses', houses_path %>
</li>

app/views/sales/_lot_fields.html.erb
<div class="nested-fields">
	<fieldset class='sub'>
		<ul>
			<li>
				<label class='next'>Lot Number</label>
				<%=f.number_field :lotnumber, step: 0.01 %>
			</li>
			<li>
				<label class='next'>Category</label>
				<%= f.collection_select(:category_id, Category.alpha, :id , :title, prompt: "Choose Category" ) %>
			</li>
			<li>
				<label class='next'>Seller</label>
				<%= f.collection_select(:seller_id, Seller.by_code, :id , :code_and_name, prompt: "Choose Seller" ) %>
			</li>
			<li>
				<label class='next'>Manufacturer</label>
				<%=f.text_field :manufacturer%>
			</li>
			<li>
				<label class='next'>Model</label>
				<%=f.text_field :model%>
			</li>
			<li>
				<label class='next'>Reserve</label>
				<%=f.number_field :reserve, step: 0.01 %>
			</li>
				<li>
				<label class='next'>Description</label>
				<%=f.text_area :description , rows: 10 %>
			</li>
			<li class='image'>
				<% if f.object.image.attached? %>
						<label>Main Image</label>
						<p><%= link_to 'remove', delete_image_lot_path(f.object.id),
																				              method: :delete,
																				              data: { confirm: 'Are you sure?' } %></p>
						<div class="image-block">
							<div class='block-image'>
								<%= image_tag f.object.image.variant(resize: "200x")%>
								<label>Change Image</label><%=f.file_field :image%>
							</div>
						</div>
				<% else %>
					<label>Main Image</label>
					<%=f.file_field :image%>
				<% end %>
			</li>
			<li>
				<% if f.object.pictures.attached? %>
					<label>Additional Images</label>
				 		<p><%= link_to 'remove all', delete_pictures_lot_path(f.object.id), 
											 	method: :delete, 
											 	data: { confirm: 'Are you sure?' } %></p>
						<div class="picture-gallery">
							<% f.object.pictures.each do |picture | %>
								<div class="lot-picture">
									<%= image_tag picture.variant(resize: "100x")%>
							<!-- to do remove attachment individually -->
								</div>
						
							<% end %>
						</div>
					<label>Add More Images</label>
					<%=f.file_field :pictures, multiple: true%>
				<% else %>
					<label>Additional Images</label>
					<%=f.file_field :pictures, multiple: true%>
				<% end %>
			</li>
			<li>
				<%= link_to_remove_association "delete lot", f %>
			</li>
		</ul>
	</fieldset>
</div>

app/views/sales/_lot_table.html.erb
<% @lots.each do |lot| %>
	<tr>
		<td><%=lot.lotnumber %></td>
		<td><%=lot.category.title %></td>
		<td><%=link_to "#{lot.manufacturer} #{lot.model}", lot_path(lot) %></td>


		<% if !@sale.active? %>
			<td><%=show_money(lot.reserve) %></td>
		<% end %>

		<% if @sale.active? || @sale.complete? %>
			<td class="money"><%= show_money(lot.selling_price)%></td>
		<% end %>




		<% if @buyer %>
			<% if @sale.active %>
				<td class="money">
					<%if @buyer.bid_for(lot).empty? %>
						no bid
					<% else %>
						<%= show_money(lot.buyer_highest_bid(@buyer).bidvalue)%>
					<% end %>
				</td>


				<td class="money">
					<%if @buyer.bid_for(lot).empty? %>
						<%= link_to 'add bid', lot_path(lot)%>
					<% else %>



						<% if lot.buyer_highest_bid(@buyer).bidvalue >= lot.highest_bid_value && lot.buyer_highest_bid(@buyer).bidvalue >= lot.reserve %>
							winning
						<% else %>
							<%=link_to 'increase bid', lot_path(lot)%>
						<% end %>
					<% end %>
				</td>
			<% end %>
		<% end %>				
	</tr>
<% end %>

app/views/sales/_sale_fields.html.erb
<%= render "shared/errors", object: @sale %>
<%= form_with(model:@sale, local:true, html: {class: "cms"}) do |f| %>
	<fieldset class='main'>
		<ul>
			<li>
				<label>House</label>
				<%= f.collection_select(:house_id, House.alpha, :id , :name, prompt: "Choose House" ) %>
			</li>
			<li class='date'>
				<label>Auction Date</label>
				<%= f.date_select :date, { order: [ :day, :month, :year]} %>
			</li>
			<li>
				<label class="nextto">Notch (£)</label>
				<%=f.number_field :notch , step: 0.01 %>
			</li>
			<li>
				<label class="nextto">Min. Transaction fee (£)</label>
				<%=f.number_field :minfee , step: 0.01 %>
			</li>
		</ul>
		<%=f.fields_for :lots do | lot | %>
			<%= render 'lot_fields', f: lot %>
		<% end %>
		<div class="links">
		  <%= link_to_add_association 'add lot', f, :lots %>
		</div>
	</fieldset>
	<%= f.submit %>
<% end %>

app/views/sales/edit.html.erb
<article>
	<header>
		<h1><%= @sale.house_and_date%> (edit)</h1>
	</header>
	<%= render 'sale_fields' %>
</article>
<% content_for(:side_links) do %>
	<%= render 'contextual_menu' %>
<% end %>

app/views/sales/index.html.erb
<article>
<%= paginate @sales %>	
	<table>
	<% unless @building.empty? %>
		<tr>
			<td colspan=8>
				<header><h1>Auctions - Building.</h1></header>
			</td>
		</tr>		
		<% @building.each do |sale| %>
			<tr>
				<td class='date'><%= short_date(sale.date) %></td>
				<td class='house'><%= sale.house.name%></td>
				<td class='lots hide'><%= pluralize(sale.lots.count, 'lot') %></td>
				<td><%= link_to "View", sale_path(sale) %></td>
				<td><%= link_to "Edit", edit_sale_path(sale) unless sale.frozen? %></td>
				<td><%=link_to 'Delete', sale, method: :delete, data: { confirm: 'Are you sure? ALL attached lots will be deleted!' } unless sale.frozen? %></td>
			</tr>
			<tr>
				<td class='left'><%= button_to 'Open Sale', activate_sale_path(sale), data: { confirm: 'Are you sure? This will publish the sale to all buyers!' }%></td>
			</tr>
		<% end %>
	<% end %>
	<% unless @live_sales.empty? %>
		<tr>
			<td colspan=8>
				<header><h1>Auctions - Live.</h1></header>
			</td>
		</tr>
			<% @live_sales.each do |sale| %>
				<tr>
					<td class='date'><%= short_date(sale.date) %></td>
					<td class='house'><%= sale.house.name%></td>
					<td class='lots hide'><%= pluralize(sale.lots.count, 'lot') %></td>
					<td class='hide'><%= pluralize(sale.vendors.uniq.count, 'vendor') %></td>
					<td class='hide'><%= pluralize(sale.bids.count, 'bid') %></td>
					<td ><%= link_to "live bidding", bid_path(sale) %></td>
					<td><%= button_to 'End Sale', deactivate_sale_path(sale), data: { confirm: 'Are you sure? This will close the auction and publish the reports!' }%></td>
				</tr>
			<% end %>
	<% end %>
	<% unless @complete_sales.empty? %>
		<tr>
			<td colspan=8>
				<header><h1>Auctions - Complete.</h1></header>
			</td>
		</tr>
			<% @complete_sales.each do |sale| %>
				<tr>
					<td class='date'><%= short_date(sale.date) %></td>
					<td class='house'><%= sale.house.name%></td>
					<td class='lots hide'><%= pluralize(sale.lots.count, 'lot') %></td>
					<td class='hide'><%= pluralize(sale.vendors.uniq.count, 'vendor') %></td>
					<td class='hide'><%= pluralize(sale.bids.count, 'bid') %></td>
					<td><%= link_to "view bids", bid_path(sale) %></td>
				</tr>
			<% end %>
	<% end %>
	</table>
	<%= paginate @sales %>
</article>

<!-- again if admin -->
<% content_for(:side_links) do %>
	<%= render 'contextual_menu' %>
<% end %>
<!-- to here -->

app/views/sales/new.html.erb
<article>
	<header>
		<h1>Create a new sale.</h1>
	</header>
	<%= render 'sale_fields' %>
</article>
<% content_for(:side_links) do %>
	<%= render 'contextual_menu' %>
<% end %>

app/views/sales/show.html.erb
<article>
	<header>
		<h1><%= nice_date(@sale.date) %> <%=@sale.house.name %></h1>
	</header>
	<% @lots.each do |lot| %>
		<div class="lot-area">
			<div class="sale-lot">
				<div class="sale-image">
					<% if lot.image.attached? %>
						<%= image_tag(lot.image.variant(resize: "200x")) %>
					<% else %>
						<h3>No Image</h3>
					<% end %>
				</div>
				<div class="sale-text">
					<h2><%=lot.lotnumber%> <%= link_to "#{lot.make_and_model}", lot_path(lot)%></h2>
					<h3><%= show_money(lot.reserve)%> reserve</h3>
				</div>
			</div>
			<p><%= simple_format(lot.description)%></p>

			<% if lot.pictures.attached? %>
			<div class="alt-images">
				<% lot.pictures.each do |picture | %>
				<div class="picture-wrapper">
					<%= image_tag(picture.variant(resize: "75x"))%>
				</div>
				<% end %>
			</div>
			<% else %>
				<h3>No additional images.</h3>
			<% end %>
		</div>
	<% end %>
</article>

<% content_for(:side_links) do %>
	<%= render 'contextual_menu' %>
<% end %>